
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import javax.swing.ButtonModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author goget
 */
public class Leaderboard extends javax.swing.JFrame {

    /**
     * Creates new form Leaderboard
     */
    public Leaderboard() {
        initComponents();
        
        this.textArea.append("Welcome to the Tournament Scoring system \nby Mohamad Ediab \n2022");
        this.btnIndividualList.setEnabled(false);
        this.btnStartEvent.setEnabled(false);
        this.btnIndividualPoints.setEnabled(false);
        this.team=new Team[5];
        team[0]=new Team(this.teamName[0],5);
        team[1]=new Team(this.teamName[1],5);
        team[2]=new Team(this.teamName[2],5);
        team[3]=new Team(this.teamName[3],5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TorI = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIndividualName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        rbTeam = new javax.swing.JRadioButton();
        rbIndividual = new javax.swing.JRadioButton();
        ComboBoxTeamSubmit = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        btnSubmitIndividual = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        ComboBoxTeam = new javax.swing.JComboBox<>();
        btnSearchTeam = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnSearchEvent = new javax.swing.JButton();
        ComboBoxEvent = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        btnIndividualList = new javax.swing.JButton();
        btnStartEvent = new javax.swing.JButton();
        btnIndividualPoints = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemLoad = new javax.swing.JMenuItem();
        itemSave = new javax.swing.JMenuItem();
        databaseLoad = new javax.swing.JMenuItem();
        itemExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1166, 727));

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Enter the participant information");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Name:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Gender:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("ID:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Is the student in a team or individual?");

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        TorI.add(rbTeam);
        rbTeam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbTeam.setText("Team");
        rbTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTeamActionPerformed(evt);
            }
        });

        TorI.add(rbIndividual);
        rbIndividual.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbIndividual.setText("Individual");
        rbIndividual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbIndividualMouseClicked(evt);
            }
        });
        rbIndividual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbIndividualActionPerformed(evt);
            }
        });

        ComboBoxTeamSubmit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Team Red", "Team Black", "Team Blue", "Team Green" }));
        ComboBoxTeamSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxTeamSubmitActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Select team");

        btnSubmitIndividual.setBackground(new java.awt.Color(240, 240, 15));
        btnSubmitIndividual.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSubmitIndividual.setText("Submit");
        btnSubmitIndividual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitIndividualActionPerformed(evt);
            }
        });

        textArea.setBackground(new java.awt.Color(0, 0, 0));
        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textArea.setForeground(new java.awt.Color(236, 236, 19));
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Search Team information");

        ComboBoxTeam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Team Red", "Team Black", "Team Blue", "Team Green" }));
        ComboBoxTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxTeamActionPerformed(evt);
            }
        });

        btnSearchTeam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSearchTeam.setText("Search");
        btnSearchTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchTeamActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Select an Event");

        btnSearchEvent.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSearchEvent.setText("Select");
        btnSearchEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchEventActionPerformed(evt);
            }
        });

        ComboBoxEvent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sporting Event", "Academic Event", "Escape room Event", "Racing Event", "Card game Event" }));

        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 0)));

        btnIndividualList.setText("Individual list");
        btnIndividualList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndividualListActionPerformed(evt);
            }
        });

        btnStartEvent.setText("Start Event");
        btnStartEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartEventActionPerformed(evt);
            }
        });

        btnIndividualPoints.setText("Individual points");
        btnIndividualPoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndividualPointsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnIndividualList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnStartEvent)
                .addGap(109, 109, 109)
                .addComponent(btnIndividualPoints)
                .addGap(26, 26, 26))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIndividualList)
                    .addComponent(btnStartEvent)
                    .addComponent(btnIndividualPoints))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(rbTeam)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rbIndividual))
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtIndividualName, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                        .addComponent(txtGender))))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ComboBoxTeamSubmit, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSubmitIndividual, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(58, 58, 58))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ComboBoxEvent, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSearchEvent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ComboBoxTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(104, 104, 104))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtIndividualName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbTeam)
                            .addComponent(rbIndividual))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ComboBoxTeamSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(btnSubmitIndividual)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboBoxTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearchTeam)
                                .addGap(76, 76, 76)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ComboBoxEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearchEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(20, 180, 1130, 470);

        jPanel2.setBackground(new java.awt.Color(242, 242, 97));
        jPanel2.setName(""); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Tournament Ranking System");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(342, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(326, 326, 326))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 20, 1130, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/istockphoto-1326423348-170667a_1166x705.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1166, 705);

        jMenu1.setText("File");

        itemLoad.setText("File Load");
        itemLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLoadActionPerformed(evt);
            }
        });
        jMenu1.add(itemLoad);

        itemSave.setText("File Save");
        itemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSaveActionPerformed(evt);
            }
        });
        jMenu1.add(itemSave);

        databaseLoad.setText("Database");
        databaseLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                databaseLoadActionPerformed(evt);
            }
        });
        jMenu1.add(databaseLoad);

        itemExit.setText("Exit");
        itemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemExitActionPerformed(evt);
            }
        });
        jMenu1.add(itemExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1169, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void rbTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTeamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbTeamActionPerformed

    private void rbIndividualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbIndividualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbIndividualActionPerformed

    private void ComboBoxTeamSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxTeamSubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxTeamSubmitActionPerformed

    private void btnSubmitIndividualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitIndividualActionPerformed
        // TODO add your handling code here:
        this.textArea.setText(" ");
        this.textArea.append("Adding new individual to ");
        
        individual=new Individual();
        individual.setID(Integer.parseInt(this.txtID.getText()));
        individual.setName(this.txtIndividualName.getText());
        individual.setGender(this.txtGender.getText());
        String team=this.ComboBoxTeamSubmit.getSelectedItem().toString();
        try
        {
         myDatabase.addIndividual(individual.getName(), team, individual.getGender(),0);
        } 
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 
        catch (IllegalAccessException ex) 
        {
            java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        for(int i=0; i<this.teamName.length; i++)
        {
            if(this.teamName[i].equalsIgnoreCase(team))
            {
                this.team[i].addIndividual(individual);
                this.textArea.append(this.team[i].getTeamName()+ " Tournament team: \n\n\n");
            }    
        }
        this.textArea.append("Member name: " +this.individual.getName() + "\n");
        this.textArea.append("Member's gender: " + this.individual.getGender() + "\n");       
        this.txtID.setText("");
        this.txtIndividualName.setText("");
        this.txtGender.setText("");
        
        
    }//GEN-LAST:event_btnSubmitIndividualActionPerformed

    private void ComboBoxTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxTeamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxTeamActionPerformed

    private void btnIndividualListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndividualListActionPerformed
        // TODO add your handling code here:
        this.textArea.setText(" ");
        this.textArea.append("Welcome to the Tournament Scoring system \\by Mohamad Ediab \\ 2022");
        this.textArea.append("Welcome to "+ event.getEventName()+ " 2022 \n\n\n");
        
        
        String[] individuals=this.event.getIndividualsList();
        System.out.println("Individuals total " + individuals.length);
        for(int i=0;i<individuals.length; i++)
        {
            this.textArea.append("No: " + (i+1) + " "+ individuals[i] + " \n" );
        }
        this.btnIndividualList.setEnabled(false);
        this.itemLoad.setEnabled(false);
        
    }//GEN-LAST:event_btnIndividualListActionPerformed

    private void btnStartEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartEventActionPerformed
        // TODO add your handling code here:
        this.textArea.setText(" ");
        this.textArea.append("Welcome to the Tournament Scoring system \\by Mohamad Ediab \\ 2022");
        this.textArea.append("Welcome to "+ event.getEventName()+ " 2022 \n\n\n");
        this.textArea.append("*********** Final results ***********" + "\n");
        String[] individuals=this.event.startEvent();
        System.out.println("Working start event");
        for(int i=0;i<individuals.length;i++)
        {
            this.textArea.append(individuals[i] + "\n");
        }
        this.btnStartEvent.setEnabled(false);
        this.btnIndividualPoints.setEnabled(true);
    }//GEN-LAST:event_btnStartEventActionPerformed

    private void btnSearchTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchTeamActionPerformed
        // TODO add your handling code here:
        this.textArea.setText("");
        this.textArea.append("Searching Team information....");
        
        String team=this.ComboBoxTeam.getSelectedItem().toString();
        for(int i=0; i<this.teamName.length; i++)
        {
            this.textArea.append(this.team[i].getTeamName()+ " Tournament Team:  \n\n\n ");
            
            for(int j=0;j<this.team[i].getCount(); j++)
            {
                this.textArea.append(this.team[i].getIndividuals(j) + "\n\n\n");
            }
        }
    }//GEN-LAST:event_btnSearchTeamActionPerformed

    private void btnSearchEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchEventActionPerformed
        
        this.textArea.setText("");
        this.textArea.append("Welcome to the Tournament Scoring system \\by Mohamad Ediab \\ 2022");
        String events=this.ComboBoxEvent.getSelectedItem().toString();
        this.event=new Event(events,this.team.length);
        event.addTeams(team[0]);
        event.addTeams(team[1]);
        event.addTeams(team[2]);
        event.addTeams(team[3]);
        this.btnIndividualList.setEnabled(true);
        this.btnStartEvent.setEnabled(true);
        this.itemLoad.setEnabled(true);
        this.itemSave.setEnabled(true);
        this.databaseLoad.setEnabled(true);
        this.textArea.append("Welcome to 2022 Tournament's " +this.event.getEventName()+ "\n\n\n");
        this.textArea.append("Individual member list is activated check out the list \n\n\n");
        event.countTeams();
        event.individualList();
        
        
    }//GEN-LAST:event_btnSearchEventActionPerformed

    private void rbIndividualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbIndividualMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rbIndividualMouseClicked

    private void itemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSaveActionPerformed
        this.textArea.setText(" ");
        this.textArea.append("Welcome to the Tournament Scoring system \\by Mohamad Ediab \\ 2022");
        this.textArea.append("***********Save file***********" + "\n");
        this.event.individualsListToFile();
    }//GEN-LAST:event_itemSaveActionPerformed

    private void btnIndividualPointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndividualPointsActionPerformed
        // TODO add your handling code here:
        this.textArea.setText(" ");
        this.textArea.append("Welcome to the Tournament Scoring system \\by Mohamad Ediab \\ 2022");
        this.textArea.append("Welcome to "+ event.getEventName()+ " 2022 \n\n\n");
        this.textArea.append("***********Individual points***********" + "\n");
        String[] individuals=this.event.eventPoints();
        System.out.println("Working individuals points");
        for(int i=0;i<individuals.length;i++)
        {
            this.textArea.append(individuals[i] + "\n");
        }
        this.btnIndividualPoints.setEnabled(false);
    }//GEN-LAST:event_btnIndividualPointsActionPerformed

    private void itemLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLoadActionPerformed
        this.textArea.setText(" ");
        this.textArea.append("Welcome to the Tournament Scoring system \\by Mohamad Ediab \\ 2022");
        this.textArea.append("***********Load file***********" + "\n");
        String[] individuals=event.individualListFromFile();
        for(int i=0; i<individuals.length;i++)
        {
            this.textArea.append(individuals[i] + " \n");
        }
        this.itemLoad.setEnabled(false);
        this.btnIndividualList.setEnabled(false);
    }//GEN-LAST:event_itemLoadActionPerformed

    private void itemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemExitActionPerformed
        System.exit(1);
    }//GEN-LAST:event_itemExitActionPerformed

    private void databaseLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_databaseLoadActionPerformed
        this.textArea.setText(" ");
        this.textArea.append("Welcome to the Tournament Scoring system \\by Mohamad Ediab \\ 2022");
        this.textArea.append("*********** Database Load ***********" + "\n");
        String individuals[];
        
        try {
            individuals=myDatabase.getIndividualsList();
            event.setIndividualsList(individuals);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        this.itemLoad.setEnabled(false);
        this.btnIndividualList.setEnabled(false);
        
    }//GEN-LAST:event_databaseLoadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Leaderboard().setVisible(true);
            }
        });
    }
    
    private Team team[];
    private Individual individual;
    private Event event;
    private String[] eventName={"Sporting event","Academic event","Escape room event","Racing event","Card game event"};
    private String[] teamName={"Team Red","Team Blue","Team Black","Team Green"};

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxEvent;
    private javax.swing.JComboBox<String> ComboBoxTeam;
    private javax.swing.JComboBox<String> ComboBoxTeamSubmit;
    private javax.swing.ButtonGroup TorI;
    private javax.swing.JButton btnIndividualList;
    private javax.swing.JButton btnIndividualPoints;
    private javax.swing.JButton btnSearchEvent;
    private javax.swing.JButton btnSearchTeam;
    private javax.swing.JButton btnStartEvent;
    private javax.swing.JButton btnSubmitIndividual;
    private javax.swing.JMenuItem databaseLoad;
    private javax.swing.JMenuItem itemExit;
    private javax.swing.JMenuItem itemLoad;
    private javax.swing.JMenuItem itemSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbIndividual;
    private javax.swing.JRadioButton rbTeam;
    private javax.swing.JTextArea textArea;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtIndividualName;
    // End of variables declaration//GEN-END:variables
}
